'use client';

import { useEffect, useState } from 'react';

const steps = [
  { number: '01', title: 'Share the brief', text: 'Choose the closest service and send the goal, deadline, source files and required format.', icon: 'brief' },
  { number: '02', title: 'Confirm the scope', text: 'We clarify the details and confirm deliverables, timing and price before work begins.', icon: 'scope' },
  { number: '03', title: 'Follow the work', text: 'A single reference and direct communication keep the project easy to follow.', icon: 'work' },
  { number: '04', title: 'Receive the files', text: 'Review the outcome and receive the agreed files in the right format.', icon: 'files' },
];

export default function ServiceProcess() {
  const [active, setActive] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setActive((value) => (value + 1) % steps.length), 2800); return () => window.clearInterval(timer); }, []);
  return <section id="process" className="overflow-hidden bg-[#073C3E] px-5 py-16 text-white md:px-10 md:py-20">
    <div className="mx-auto max-w-[1440px]"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#DDF65C]">How the work moves</p><h2 className="mt-5 text-5xl font-black leading-[.88] tracking-[-.065em] md:text-7xl">One brief.<br />Four clear moves.</h2><p className="mt-6 max-w-md leading-7 text-white/55">Tap a stage to see the handoff. The process stays visible without sending you to another page.</p><a href="/start" className="mt-8 inline-flex bg-[#DDF65C] px-6 py-4 text-sm font-black text-[#102321]">Start with your brief →</a></div>
      <div><div className="relative min-h-[360px] overflow-hidden border border-white/15 bg-[#061E1E] p-6 md:min-h-[430px] md:p-10"><div className="absolute inset-0 opacity-20 process-grid" /><div className="relative flex min-h-[300px] items-center justify-center md:min-h-[350px]"><svg viewBox="0 0 760 300" aria-hidden="true" className="w-full"><path d="M80 150H680" fill="none" stroke="rgba(255,255,255,.18)" strokeWidth="2" strokeDasharray="8 10"/><path d="M80 150H680" fill="none" stroke="#DDF65C" strokeWidth="3" strokeDasharray="600" strokeDashoffset={600 - (active / 3) * 600} className="transition-all duration-700"/>{steps.map((step,index) => { const x = 80 + index * 200; return <g key={step.number} onClick={() => setActive(index)} className="cursor-pointer"><circle cx={x} cy="150" r={active === index ? 38 : 28} fill={active === index ? '#DDF65C' : '#102F2E'} stroke={active === index ? '#DDF65C' : 'rgba(255,255,255,.3)'} strokeWidth="2" className="transition-all duration-500"/><text x={x} y="156" textAnchor="middle" fill={active === index ? '#102321' : '#fff'} fontSize="15" fontWeight="900">{step.number}</text><text x={x} y={active === index ? 224 : 214} textAnchor="middle" fill={active === index ? '#DDF65C' : 'rgba(255,255,255,.45)'} fontSize="12" fontWeight="800" className="transition-all">{step.title}</text></g>; })}<circle cx={80 + active * 200} cy="150" r="48" fill="none" stroke="#DDF65C" strokeWidth="2" className="process-pulse" /></svg><div className="absolute left-1/2 top-5 w-[min(88%,520px)] -translate-x-1/2 border-l-4 border-[#DDF65C] bg-white p-5 text-[#102321] shadow-2xl transition-all md:top-0"><div className="flex items-center gap-4"><ProcessIcon type={steps[active].icon} /><div><small className="font-black uppercase tracking-[.14em] text-[#F06449]">Stage {steps[active].number}</small><strong className="mt-1 block text-2xl">{steps[active].title}</strong><p className="mt-2 text-sm leading-6 text-black/55">{steps[active].text}</p></div></div></div></div></div>
        <div className="grid grid-cols-4 gap-px bg-white/15">{steps.map((step,index) => <button key={step.number} onClick={() => setActive(index)} className={`px-2 py-4 text-[10px] font-black uppercase tracking-[.1em] transition ${active === index ? 'bg-[#DDF65C] text-[#102321]' : 'bg-[#073C3E] text-white/45 hover:text-white'}`}>{step.number}<span className="hidden md:inline"> / {step.title}</span></button>)}</div></div></div></div>
  </section>;
}

function ProcessIcon({ type }: { type: string }) { return <span className="grid h-12 w-12 shrink-0 place-items-center bg-[#DDF65C]"><svg viewBox="0 0 32 32" className="h-7 w-7 fill-none stroke-current" strokeWidth="1.7">{type === 'brief' && <><path d="M8 4h12l4 4v20H8z"/><path d="M20 4v5h5M12 14h8M12 19h8"/></>}{type === 'scope' && <><circle cx="16" cy="16" r="11"/><path d="m11 16 3 3 7-8"/></>}{type === 'work' && <><path d="M4 8h24v17H4zM10 8V5h12v3"/><path d="M4 15h24M13 15v3h6v-3"/></>}{type === 'files' && <><path d="M7 5h12l5 5v17H7z"/><path d="M19 5v6h6M11 16h9M11 21h9"/></>}</svg></span>; }
