'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { MediaAsset } from '../../lib/content-types';

export default function MediaLibrary({ initialAssets }: { initialAssets: MediaAsset[] }) {
  const router = useRouter(); const [assets, setAssets] = useState(initialAssets); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const file = data.get('file'); if (!(file instanceof File) || !file.size) return; setBusy('upload'); setError(''); setNotice(''); const response = await fetch('/api/admin/media', { method: 'POST', body: data }); const payload = await response.json().catch(() => ({})) as { error?: string; asset?: MediaAsset }; if (!response.ok || !payload.asset) setError(payload.error || 'Upload failed.'); else { setAssets((current) => [payload.asset!, ...current]); setNotice('Media uploaded and ready for the site editor.'); form.reset(); router.refresh(); } setBusy(''); }
  async function remove(asset: MediaAsset) { if (!window.confirm(`Delete ${asset.file_name}? Existing pages using its URL will lose the media.`)) return; setBusy(asset.id); const response = await fetch(`/api/admin/media/${asset.id}`, { method: 'DELETE' }); if (response.ok) { setAssets((current) => current.filter((item) => item.id !== asset.id)); setNotice('Media deleted.'); router.refresh(); } else { const payload = await response.json().catch(() => ({})) as { error?: string }; setError(payload.error || 'Delete failed.'); } setBusy(''); }
  return <div className="grid gap-6"><section className="bg-[#073C3E] p-7 text-white md:p-10"><p className="text-xs font-black uppercase tracking-[.15em] text-[#DDF65C]">Media library</p><h1 className="mt-3 text-5xl font-black tracking-[-.06em] md:text-7xl">Images, video and audio, ready to place.</h1><p className="mt-5 max-w-2xl text-sm leading-6 text-white/55">Upload technical photography, renderings, diagrams, short video, voice files and background music. Assets appear immediately inside the site and intro editors.</p></section>
    <form onSubmit={upload} className="grid gap-5 bg-white p-7 lg:grid-cols-[1fr_1fr_1.3fr_auto] lg:items-end"><label className="text-xs font-black">Title<input name="title" className="elx-field" placeholder="e.g. Intro background music" /></label><label className="text-xs font-black">Alt text / note<input name="altText" className="elx-field" placeholder="Describe the visual or audio use" /></label><label className="text-xs font-black">Media file<input name="file" type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime,audio/mpeg,audio/mp3,audio/wav,audio/x-wav,audio/ogg,audio/mp4,audio/aac,audio/flac" className="elx-field" required /></label><button disabled={busy === 'upload'} className="bg-[#102321] px-6 py-4 text-sm font-black text-white disabled:opacity-40">{busy === 'upload' ? 'Uploading...' : 'Upload media'}</button><p className="text-xs leading-5 text-black/45 lg:col-span-4">JPG, PNG, WebP, GIF, MP4, WebM, MOV, MP3, WAV, OGG, AAC or FLAC. Maximum 100 MB. Use compressed web-ready video and audio for performance.</p></form>
    {(error || notice) && <p className={`p-4 text-sm font-bold ${error ? 'bg-red-50 text-red-700' : 'bg-green-50 text-green-800'}`}>{error || notice}</p>}
    <section className="bg-white p-6"><div className="flex items-end justify-between"><h2 className="text-3xl font-black">Library</h2><span className="text-xs text-black/40">{assets.length} assets</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{assets.map((asset) => <article key={asset.id} className="border border-black/10"><div className="aspect-video overflow-hidden bg-[#102321]">{asset.kind === 'video' ? <video src={asset.public_url} controls preload="metadata" className="h-full w-full object-cover" /> : asset.kind === 'audio' ? <div className="grid h-full place-items-center p-4 text-white"><p className="text-xs font-black uppercase tracking-[.16em] text-[#DDF65C]">Audio</p><audio src={asset.public_url} controls preload="metadata" className="mt-4 w-full" /></div> : <img src={asset.public_url} alt={asset.alt_text || asset.title} className="h-full w-full object-cover" />}</div><div className="p-4"><p className="truncate font-black">{asset.title || asset.file_name}</p><p className="mt-1 text-xs text-black/40">{asset.kind} / {(asset.file_size / 1024 / 1024).toFixed(1)} MB</p><div className="mt-4 flex gap-4 text-xs font-black"><button onClick={() => navigator.clipboard.writeText(asset.public_url)}>Copy URL</button><button disabled={busy === asset.id} onClick={() => remove(asset)} className="text-red-700">Delete</button></div></div></article>)}</div>{assets.length === 0 && <p className="mt-8 text-sm text-black/45">No uploaded media yet. The homepage can still use its bundled technical images.</p>}</section>
  </div>;
}
