'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';

export type ClientRow = { id: string; name: string; email: string; phone: string; country: string; status: string; createdAt: string; lastSignIn: string | null; orders: number; active: number; quoted: Record<string, number> };

export default function ClientsClient({ clients }: { clients: ClientRow[] }) {
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('all');
  const filtered = useMemo(() => clients.filter((client) => `${client.name} ${client.email} ${client.phone} ${client.country}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'all' || (filter === 'active' ? client.active > 0 : client.orders === 0))), [clients, search, filter]);
  return <div className="grid gap-6"><section className="bg-white p-7 md:p-9"><p className="text-xs font-black uppercase tracking-[.14em] text-[#F06449]">Client directory</p><div className="mt-2 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-5xl font-black tracking-[-.06em]">Accounts & value</h1><p className="mt-3 text-sm text-black/50">Identity, project activity and quoted value—without exposing credentials.</p></div><span className="text-3xl font-black">{clients.length}</span></div><div className="mt-7 grid gap-3 md:grid-cols-[1fr_220px]"><input className="elx-field" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name, email, phone or country…" /><select className="elx-field" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All clients</option><option value="active">Active projects</option><option value="empty">No projects</option></select></div></section>
    <section className="overflow-x-auto bg-white p-5 md:p-7"><table className="w-full min-w-[980px] text-left text-sm"><thead><tr className="text-[10px] font-black uppercase tracking-[.1em] text-black/35"><th className="p-3">Client</th><th className="p-3">Contact</th><th className="p-3">Projects</th><th className="p-3">Quoted</th><th className="p-3">Last sign-in</th><th className="p-3">Account</th></tr></thead><tbody>{filtered.map((client) => <tr key={client.id} className="border-t border-black/10"><td className="p-3"><strong className="block">{client.name}</strong><small className="text-black/40">Since {new Date(client.createdAt).toLocaleDateString()}</small></td><td className="p-3"><span className="block">{client.email}</span><small className="text-black/40">{client.phone || client.country || 'No profile details'}</small></td><td className="p-3"><strong>{client.orders}</strong><small className="ml-2 text-black/40">{client.active} active</small></td><td className="p-3">{Object.entries(client.quoted).map(([currency, total]) => <span key={currency} className="mr-2 block font-bold">{currency} {total.toLocaleString()}</span>)}{Object.keys(client.quoted).length === 0 && '—'}</td><td className="p-3">{client.lastSignIn ? new Date(client.lastSignIn).toLocaleString() : 'Never'}</td><td className="p-3"><span className={`px-3 py-2 text-xs font-black capitalize ${client.status === 'active' ? 'bg-[#E8F3E7] text-[#164F22]' : 'bg-[#F5F2E8]'}`}>{client.status}</span></td></tr>)}</tbody></table>{filtered.length === 0 && <p className="p-8 text-center text-black/40">No clients match this view.</p>}</section>
    <div className="flex justify-end"><Link href="/admin/orders" className="bg-[#102321] px-5 py-3 text-sm font-black text-white">Open client orders →</Link></div></div>;
}
