'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { HomepageContent, MediaAsset } from '../../lib/content-types';

type Section = 'hero' | 'carousel' | 'stats' | 'intro' | 'services' | 'workflow' | 'cta' | 'footer';
const sectionNames: Record<Section, string> = { hero: 'Hero', carousel: 'Service carousel', stats: 'Trust statistics', intro: 'Introduction', services: 'Services heading', workflow: 'Workflow heading', cta: 'Project call-to-action', footer: 'Footer' };

export default function VisualEditor({ initialContent, media }: { initialContent: HomepageContent; media: MediaAsset[] }) {
  const router = useRouter(); const [content, setContent] = useState(initialContent); const [selected, setSelected] = useState<Section>('hero'); const [slideIndex, setSlideIndex] = useState(0); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  const update = (key: keyof HomepageContent, value: unknown) => setContent((current) => ({ ...current, [key]: value }));
  const updateSlide = (key: string, value: string) => setContent((current) => ({ ...current, carousel: current.carousel.map((slide, index) => index === slideIndex ? { ...slide, [key]: value } : slide) }));
  async function save() { setBusy(true); setError(''); setNotice(''); const response = await fetch('/api/admin/site-content/homepage', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ content }) }); const payload = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) setError(payload.error || 'Could not save the homepage.'); else { setNotice('Homepage published.'); router.refresh(); } setBusy(false); }
  const slide = content.carousel[slideIndex];
  return <div className="grid gap-5">
    <section className="flex flex-col justify-between gap-5 bg-[#073C3E] p-7 text-white md:flex-row md:items-end md:p-10"><div><p className="text-xs font-black uppercase tracking-[.15em] text-[#DDF65C]">Visual site editor</p><h1 className="mt-3 text-5xl font-black tracking-[-.06em] md:text-7xl">Click the page. Edit the block.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-white/55">This preview mirrors the homepage structure. Select a section on the left, change it on the right, then publish.</p></div><div className="flex gap-3"><a href="/" target="_blank" className="border border-white/20 px-5 py-3 text-sm font-black">Open website ↗</a><button onClick={save} disabled={busy} className="bg-[#DDF65C] px-5 py-3 text-sm font-black text-[#102321] disabled:opacity-40">{busy ? 'Publishing...' : 'Publish changes'}</button></div></section>
    {(notice || error) && <p className={`p-4 text-sm font-bold ${error ? 'bg-red-50 text-red-700' : 'bg-green-50 text-green-800'}`}>{error || notice}</p>}
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
      <div className="overflow-hidden bg-[#F5F2E8] shadow-sm">
        <Editable selected={selected === 'hero'} onClick={() => setSelected('hero')}><section className="bg-[#073C3E] p-10 text-white"><p className="text-xs font-black uppercase tracking-[.15em] text-[#DDF65C]">{content.heroEyebrow}</p><h2 className="mt-5 text-7xl font-black leading-[.8] tracking-[-.08em]">{content.heroTitle}<br /><span className="text-[#DDF65C]">{content.heroAccent}</span></h2><p className="mt-7 max-w-xl leading-7 text-white/65">{content.heroDescription}</p></section></Editable>
        <Editable selected={selected === 'carousel'} onClick={() => setSelected('carousel')}><section className="relative min-h-[430px] bg-[#102321] bg-cover bg-center p-10 text-white" style={slide?.mediaType === 'image' ? { backgroundImage: `linear-gradient(90deg,rgba(4,20,19,.94),rgba(4,20,19,.2)),url(${slide.mediaUrl})` } : undefined}>{slide?.mediaType === 'video' && <video src={slide.mediaUrl} muted className="absolute inset-0 h-full w-full object-cover opacity-40" />}<div className="relative mt-36"><p className="text-xs font-black uppercase tracking-[.15em] text-[#DDF65C]">{slide?.eyebrow}</p><h3 className="mt-4 max-w-2xl text-5xl font-black leading-[.9] tracking-[-.06em]">{slide?.title}</h3><p className="mt-4 max-w-lg text-white/60">{slide?.text}</p></div></section></Editable>
        <Editable selected={selected === 'stats'} onClick={() => setSelected('stats')}><section className="grid grid-cols-4 gap-4 p-8">{content.stats.map((item) => <div key={item.label}><strong className="text-3xl">{item.value}</strong><p className="mt-1 text-xs text-black/45">{item.label}</p></div>)}</section></Editable>
        <Editable selected={selected === 'intro'} onClick={() => setSelected('intro')}><section className="grid min-h-[400px] md:grid-cols-[.9fr_1.1fr]"><div className="relative min-h-72 overflow-hidden bg-[#102321]">{content.introMediaType === 'video' ? <video src={content.introMediaUrl} muted className="absolute inset-0 h-full w-full object-cover" /> : <img src={content.introMediaUrl} alt="" className="absolute inset-0 h-full w-full object-cover" />}<p className="absolute bottom-6 left-6 text-xs font-black uppercase tracking-[.15em] text-[#DDF65C]">{content.introEyebrow}</p></div><div className="flex flex-col justify-center p-10"><h3 className="text-4xl font-black leading-none tracking-[-.05em]">{content.introTitle}</h3><p className="mt-5 leading-7 text-black/55">{content.introBody}</p></div></section></Editable>
        <Editable selected={selected === 'services'} onClick={() => setSelected('services')}><section className="bg-white p-10"><p className="text-xs font-black uppercase tracking-[.15em] text-[#F06449]">{content.servicesEyebrow}</p><h3 className="mt-4 text-5xl font-black leading-none tracking-[-.06em]">{content.servicesTitle}</h3></section></Editable>
        <Editable selected={selected === 'workflow'} onClick={() => setSelected('workflow')}><section className="bg-[#073C3E] p-10 text-white"><p className="text-xs font-black uppercase tracking-[.15em] text-[#DDF65C]">{content.workflowEyebrow}</p><h3 className="mt-4 text-5xl font-black leading-none tracking-[-.06em]">{content.workflowTitle}</h3></section></Editable>
        <Editable selected={selected === 'cta'} onClick={() => setSelected('cta')}><section className="bg-[#DDF65C] p-10"><p className="text-xs font-black uppercase tracking-[.15em]">{content.ctaEyebrow}</p><h3 className="mt-4 text-5xl font-black leading-none tracking-[-.06em]">{content.ctaTitle}</h3><p className="mt-5 max-w-xl text-black/60">{content.ctaBody}</p></section></Editable>
        <Editable selected={selected === 'footer'} onClick={() => setSelected('footer')}><section className="bg-[#102321] p-8 text-white"><strong className="text-2xl">Elx.Studio</strong><p className="mt-2 text-sm text-white/45">{content.footerTagline}</p></section></Editable>
      </div>
      <aside className="bg-white p-6 xl:sticky xl:top-20 xl:self-start"><p className="text-xs font-black uppercase tracking-[.15em] text-[#F06449]">Editing</p><h2 className="mt-2 text-3xl font-black">{sectionNames[selected]}</h2><div className="mt-6">{selected === 'hero' && <><Text label="Eyebrow" value={content.heroEyebrow} onChange={(v) => update('heroEyebrow', v)} /><Text label="Main title" value={content.heroTitle} onChange={(v) => update('heroTitle', v)} /><Text label="Accent title" value={content.heroAccent} onChange={(v) => update('heroAccent', v)} /><Area label="Description" value={content.heroDescription} onChange={(v) => update('heroDescription', v)} /><Text label="Primary button" value={content.heroPrimaryLabel} onChange={(v) => update('heroPrimaryLabel', v)} /><Text label="Secondary button" value={content.heroSecondaryLabel} onChange={(v) => update('heroSecondaryLabel', v)} /></>}
        {selected === 'carousel' && <><div className="flex flex-wrap gap-2">{content.carousel.map((item, index) => <button key={item.id} onClick={() => setSlideIndex(index)} className={`px-3 py-2 text-xs font-black ${index === slideIndex ? 'bg-[#DDF65C]' : 'bg-[#F5F2E8]'}`}>{index + 1}</button>)}<button onClick={() => { const next = [...content.carousel, { id: crypto.randomUUID(), eyebrow: 'New service', title: 'New slide title', text: 'Describe the service.', mediaUrl: '/images/technical-render.jpg', mediaType: 'image' as const, link: '/services' }]; update('carousel', next); setSlideIndex(next.length - 1); }} className="bg-[#102321] px-3 py-2 text-xs font-black text-white">+ Slide</button></div>{slide && <><Text label="Eyebrow" value={slide.eyebrow} onChange={(v) => updateSlide('eyebrow', v)} /><Text label="Title" value={slide.title} onChange={(v) => updateSlide('title', v)} /><Area label="Description" value={slide.text} onChange={(v) => updateSlide('text', v)} /><Text label="Destination" value={slide.link} onChange={(v) => updateSlide('link', v)} /><label className="mt-5 block text-xs font-black">Media<select className="elx-field" value={slide.mediaUrl} onChange={(event) => { const asset = media.find((item) => item.public_url === event.target.value); updateSlide('mediaUrl', event.target.value); if (asset) updateSlide('mediaType', asset.kind); }}><option value={slide.mediaUrl}>Current media</option>{media.map((asset) => <option key={asset.id} value={asset.public_url}>{asset.title || asset.file_name} ({asset.kind})</option>)}</select></label><button onClick={() => { if (content.carousel.length < 2) return; update('carousel', content.carousel.filter((_, index) => index !== slideIndex)); setSlideIndex(0); }} className="mt-6 text-xs font-black text-red-700">Delete this slide</button></>}</>}
        {selected === 'stats' && <div className="grid gap-4">{content.stats.map((item, index) => <div key={index} className="grid grid-cols-[.35fr_1fr] gap-3"><input className="elx-field" value={item.value} onChange={(e) => update('stats', content.stats.map((row, i) => i === index ? { ...row, value: e.target.value } : row))} /><input className="elx-field" value={item.label} onChange={(e) => update('stats', content.stats.map((row, i) => i === index ? { ...row, label: e.target.value } : row))} /></div>)}</div>}
        {selected === 'intro' && <><Text label="Eyebrow" value={content.introEyebrow} onChange={(v) => update('introEyebrow', v)} /><Area label="Title" value={content.introTitle} onChange={(v) => update('introTitle', v)} /><Area label="Body" value={content.introBody} onChange={(v) => update('introBody', v)} /><label className="mt-5 block text-xs font-black">Technical visual<select className="elx-field" value={content.introMediaUrl} onChange={(event) => { const asset = media.find((item) => item.public_url === event.target.value); update('introMediaUrl', event.target.value); if (asset) update('introMediaType', asset.kind); }}><option value={content.introMediaUrl}>Current visual</option>{media.map((asset) => <option key={asset.id} value={asset.public_url}>{asset.title || asset.file_name} ({asset.kind})</option>)}</select></label></>}
        {selected === 'services' && <><Text label="Eyebrow" value={content.servicesEyebrow} onChange={(v) => update('servicesEyebrow', v)} /><Area label="Heading" value={content.servicesTitle} onChange={(v) => update('servicesTitle', v)} /><p className="mt-5 bg-[#F5F2E8] p-4 text-xs leading-5 text-black/55">Individual service cards are managed under Services.</p></>}
        {selected === 'workflow' && <><Text label="Eyebrow" value={content.workflowEyebrow} onChange={(v) => update('workflowEyebrow', v)} /><Area label="Heading" value={content.workflowTitle} onChange={(v) => update('workflowTitle', v)} /></>}
        {selected === 'cta' && <><Text label="Eyebrow" value={content.ctaEyebrow} onChange={(v) => update('ctaEyebrow', v)} /><Area label="Title" value={content.ctaTitle} onChange={(v) => update('ctaTitle', v)} /><Area label="Body" value={content.ctaBody} onChange={(v) => update('ctaBody', v)} /></>}
        {selected === 'footer' && <Area label="Footer tagline" value={content.footerTagline} onChange={(v) => update('footerTagline', v)} />}</div></aside>
    </div>
  </div>;
}

function Editable({ selected, onClick, children }: { selected: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" onClick={onClick} className={`relative block w-full text-left outline-none ${selected ? 'ring-4 ring-inset ring-[#F06449]' : 'hover:ring-2 hover:ring-inset hover:ring-[#F06449]/40'}`}>{children}<span className="absolute right-3 top-3 bg-[#102321] px-2 py-1 text-[10px] font-black uppercase text-white">Edit</span></button>; }
function Text({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="mt-5 block text-xs font-black">{label}<input className="elx-field" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function Area({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="mt-5 block text-xs font-black">{label}<textarea className="elx-field min-h-24 resize-y" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
