export const SITE_STRINGS = [
  'Get It Right',
  'Technical and professional project support for calculations, STEM, architecture, CAD, 3D rendering, writing, finance and business work.',
  'Writing and Documentation',
  'STEM Support',
  'Architecture and Design',
  'CAD Drafting',
  '3D Modeling and Rendering',
  'Finance and Accounting',
  'Business and Professional Services',
  'Work through complex calculations',
  'Get structured support for mathematics, science, engineering, data and technical problem-solving.',
  'Mathematical equations viewed through a magnifying glass',
  'Develop precise drawings and plans',
  'Move from an early idea to clear floor plans, CAD drawings, models and technical documentation.',
  'Architectural plans with rulers and a protractor',
  'Turn numbers into useful decisions',
  'Build budgets, forecasts, reports and Excel models that make the story behind the figures easier to see.',
  'A laptop displaying analytical charts and financial data',
  'Create polished visual outcomes',
  'Present concepts with refined 3D models, renderings, diagrams, boards and presentation-ready visuals.',
  'A geometric three-dimensional digital render',
  'Share the brief',
  'Tell us the goal, required format, deadline and any instructions you already have.',
  'Confirm the plan',
  'We clarify open questions and agree on the deliverables, timing and price.',
  'Follow the progress',
  'Continue on WhatsApp for direct communication while the work takes shape.',
  'Receive the files',
  'Review the completed work and receive your final files in the agreed format.',
  'Expertise',
  'How it works',
  'Send a brief',
  'Start a project',
  'Technical & professional project support',
  'Get it',
  'right.',
  "Bring us the difficult brief—the calculations, drawings, models, reports and details. We'll help turn it into clear, polished work you can use with confidence.",
  'Send your brief',
  'Explore our expertise',
  'CAD + 3D',
  'STEM + analysis',
  'Reports + finance',
  'service areas',
  'reference for every brief',
  'Direct',
  'WhatsApp communication',
  'Flexible',
  'delivery formats',
  'Built around your brief',
  "Your project can be complex. The process shouldn't be.",
  'No endless searching for different specialists. No wondering what happens next. Start with one clear brief and move forward with the right support around the work.',
  'Everything you need',
  'From first calculation to final presentation.',
  'Also available',
  'Reports & proposals',
  'Editing & formatting',
  'Research support',
  'Pitch decks',
  'Company profiles',
  'Resumes & presentations',
  'A clear path from brief to done.',
  'Start your project →',
  'Ready when you are',
  "Let's get to work.",
  "Share the context, deadline and format you have in mind. We'll review the details and continue with you on WhatsApp.",
  'Have supporting files?',
  'Paste a Drive, Dropbox, WeTransfer or OneDrive link—or send the files when we continue on WhatsApp.',
  'A calculator placed over printed charts and analytical reports',
  'Full name',
  'Your name',
  'WhatsApp number',
  'Email',
  '(optional)',
  'What do you need?',
  'Select a service',
  'When do you need it?',
  'Today, Friday, 24 hours...',
  'Budget range',
  '$50–$200, flexible...',
  'Supporting files',
  'Paste a Drive, Dropbox, WeTransfer or OneDrive link',
  'Tell us about the project',
  'Describe the goal, requirements, format, software, references and finished files you expect...',
  'Sending your brief...',
  'Send my brief and continue on WhatsApp →',
  'We could not send your brief just now. Please try again or contact us directly on WhatsApp.',
  'We have your brief. Reference:',
  "Continue on WhatsApp and we'll take it from here.",
  'Continue on WhatsApp ↗',
  'Professional and technical project support.',
  'Terms',
  'Privacy',
  'Academic integrity',
  'Back to Elx Studio',
  'Terms of Service',
  'Elx Studio is a project support platform owned by Elx Holdings. By submitting a project request, you agree to provide accurate instructions, communicate respectfully, and use all deliverables responsibly.',
  'Services',
  'Elx Studio may provide documentation, writing support, editing, STEM support, CAD support, design support, 3D rendering, finance, accounting and professional documentation services. Final scope, deadline and price are confirmed after review of the client brief.',
  'Payments',
  'Work begins after the agreed quote and payment instructions are confirmed. Manual payment links, invoices or other accepted payment methods may be used during the MVP stage.',
  'Revisions',
  'Reasonable revisions may be provided when they remain within the original project scope. New requirements may require an additional quote.',
  'Privacy Policy',
  'Elx Studio collects information submitted through project forms, including name, contact details, service category, project instructions, deadlines and file links. This information is used to review requests, prepare quotes, communicate with clients and deliver services.',
  'Data handling',
  'Client information should only be accessed by authorized Elx Holdings staff or approved project contributors. Client files and instructions should not be shared publicly.',
  'Contact',
  'For privacy questions, contact Elx Holdings through the official business communication channel listed on the website.',
  'Academic Integrity Policy',
  'Elx Studio supports learning, documentation, editing, formatting, research guidance, modelling, tutoring-style explanations and professional support. Clients are responsible for following their institution, employer or organization rules.',
  'Responsible use',
  'Academic materials should be used as learning support, drafts, examples, study guidance or editing assistance. Elx Studio does not support impersonation, exam cheating, fraud, or misuse of deliverables.',
  'Client responsibility',
  'By submitting a request, the client confirms that they will use any materials responsibly and make final decisions about submission, publication or professional use.',
] as const;
