'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';

export type TeamRow = { id: string; name: string; email: string; roles: string[]; status: string; assignedOrders: number; activeTasks: number; skills: string[]; availability: string | null };
const availableRoles = ['super_admin', 'admin', 'project_manager', 'expert', 'client'];

export default function TeamClient({ members, canManage }: { members: TeamRow[]; canManage: boolean }) {
  const router = useRouter(); const [editing, setEditing] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  function begin(member: TeamRow) { setEditing(member.id); setSelected(member.roles); setError(''); }
  function toggle(role: string) { setSelected((current) => current.includes(role) ? current.filter((item) => item !== role) : [...current, role]); }
  async function save() { setBusy(true); setError(''); const response = await fetch(`/api/admin/team/${editing}/roles`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ roles: selected }) }); const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) setError(body.error || 'Roles could not be updated.'); else { setEditing(''); router.refresh(); } setBusy(false); }
  return <div className="grid gap-6"><section className="bg-[#073C3E] p-7 text-white md:p-10"><p className="text-xs font-black uppercase tracking-[.14em] text-[#DDF65C]">People & capacity</p><h1 className="mt-2 text-5xl font-black tracking-[-.06em] md:text-7xl">Team workload.</h1><p className="mt-5 max-w-2xl text-sm leading-6 text-white/55">Roles control access. Assignments reveal actual workload; they are not inferred from geography, rates or profile labels.</p></section><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{members.map((member) => <article key={member.id} className="bg-white p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-black">{member.name}</h2><p className="mt-1 text-xs text-black/40">{member.email}</p></div><span className="bg-[#F5F2E8] px-3 py-2 text-[10px] font-black uppercase">{member.status}</span></div><div className="mt-5 flex flex-wrap gap-2">{member.roles.map((role) => <span key={role} className="bg-[#DDF65C] px-3 py-2 text-[10px] font-black uppercase">{role.replaceAll('_', ' ')}</span>)}</div><div className="mt-6 grid grid-cols-2 gap-2"><Fact label="Orders" value={member.assignedOrders} /><Fact label="Active tasks" value={member.activeTasks} /></div>{member.availability && <p className="mt-4 text-xs font-bold capitalize text-black/45">{member.availability}</p>}{member.skills.length > 0 && <p className="mt-3 text-xs leading-5 text-black/45">{member.skills.slice(0, 5).join(' · ')}</p>}{canManage && <button onClick={() => begin(member)} className="mt-5 text-xs font-black underline">Manage roles</button>}{editing === member.id && <div className="mt-5 border-t border-black/10 pt-4"><div className="grid gap-2">{availableRoles.map((role) => <label key={role} className="flex gap-3 text-xs font-bold"><input type="checkbox" checked={selected.includes(role)} onChange={() => toggle(role)} />{role.replaceAll('_', ' ')}</label>)}</div><div className="mt-4 flex gap-3"><button onClick={() => void save()} disabled={busy} className="bg-[#102321] px-4 py-2 text-xs font-black text-white">Save</button><button onClick={() => setEditing('')} className="text-xs font-black">Cancel</button></div>{error && <p className="mt-3 text-xs font-bold text-red-700">{error}</p>}</div>}</article>)}</section>{members.length === 0 && <p className="bg-white p-8 text-black/45">No team roles have been granted yet.</p>}</div>;
}
function Fact({ label, value }: { label: string; value: number }) { return <div className="bg-[#F5F2E8] p-3"><strong className="text-2xl">{value}</strong><span className="mt-1 block text-[9px] font-black uppercase text-black/35">{label}</span></div>; }
