'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { DigitalProduct, MediaAsset, ProductPackage } from '../../lib/content-types';

export type ProductRequest = { id: string; name: string; email: string; whatsapp: string; notes: string | null; status: string; package_label: string | null; quoted_price: number | null; currency: string | null; created_at: string; product: { title: string } | null };
const requestStatuses = ['new','contacted','awaiting_payment','paid','fulfilled','cancelled'];

export default function ShopManager({ initialProducts, requests, media }: { initialProducts: DigitalProduct[]; requests: ProductRequest[]; media: MediaAsset[] }) {
  const router = useRouter(); const [products, setProducts] = useState(initialProducts); const [selectedId, setSelectedId] = useState(initialProducts[0]?.id || ''); const [editing, setEditing] = useState<DigitalProduct | null>(initialProducts[0] || null); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [section, setSection] = useState('essentials'); const [form, setForm] = useState({ title: '', slug: '', summary: '', price: '49' });
  useEffect(() => { setProducts(initialProducts); setEditing((current) => initialProducts.find((item) => item.id === current?.id) || initialProducts[0] || null); setSelectedId((current) => initialProducts.some((item) => item.id === current) ? current : initialProducts[0]?.id || ''); }, [initialProducts]);
  function choose(id: string) { setSelectedId(id); setEditing(products.find((item) => item.id === id) || null); setSection('essentials'); }
  async function call(url: string, options: RequestInit, action: string) { setBusy(action); setError(''); setNotice(''); const response = await fetch(url, options); const payload = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) setError(payload.error || 'The action failed.'); else { setNotice('Saved successfully.'); router.refresh(); } setBusy(''); return response.ok; }
  async function create(event: FormEvent) { event.preventDefault(); const ok = await call('/api/admin/products', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }, 'create'); if (ok) setForm({ title: '', slug: '', summary: '', price: '49' }); }
  async function save(event: FormEvent) { event.preventDefault(); if (!editing) return; await call(`/api/admin/products/${editing.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(editing) }, 'save'); }
  async function requestStatus(id: string, status: string) { await call(`/api/admin/product-requests/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }, id); }
  const set = <K extends keyof DigitalProduct>(key: K, value: DigitalProduct[K]) => editing && setEditing({ ...editing, [key]: value });
  return <div className="grid gap-6"><section className="bg-[#073C3E] p-7 text-white md:p-10"><p className="text-xs font-black uppercase tracking-[.15em] text-[#DDF65C]">Shop manager</p><div className="mt-3 flex flex-wrap items-end justify-between gap-6"><div><h1 className="text-5xl font-black tracking-[-.06em] md:text-7xl">Plans, packages and buyers.</h1><p className="mt-5 max-w-2xl text-sm leading-6 text-white/55">Create the catalogue, assign model media, define drawing packages and manage every purchase request from one place.</p></div><div className="grid grid-cols-3 gap-px bg-white/15 text-center"><Stat value={products.length} label="Products" /><Stat value={products.filter((item) => item.status === 'published').length} label="Live" /><Stat value={requests.filter((item) => item.status === 'new').length} label="New leads" /></div></div></section>
    {(error || notice) && <p className={`p-4 text-sm font-bold ${error ? 'bg-red-50 text-red-700' : 'bg-green-50 text-green-800'}`}>{error || notice}</p>}
    <div className="grid gap-6 xl:grid-cols-[330px_1fr]"><aside className="bg-[#102321] p-6 text-white"><div className="flex items-end justify-between"><h2 className="text-3xl font-black">Products</h2><span className="text-xs text-white/35">{products.length}</span></div><div className="mt-5 max-h-[620px] space-y-2 overflow-y-auto">{products.map((product) => <button key={product.id} onClick={() => choose(product.id)} className={`grid w-full grid-cols-[58px_1fr] gap-3 p-3 text-left ${selectedId === product.id ? 'bg-[#DDF65C] text-[#102321]' : 'bg-white/5'}`}><div className="aspect-square overflow-hidden bg-black/20">{product.cover_url && <img src={product.cover_url} alt="" className="h-full w-full object-cover" />}</div><span><small className="text-[9px] font-black uppercase tracking-[.12em] opacity-50">{product.status} · {product.sku || 'No SKU'}</small><strong className="mt-1 block leading-tight">{product.title}</strong><small className="mt-1 block opacity-55">{product.currency} {product.price}</small></span></button>)}</div><form onSubmit={create} className="mt-7 border-t border-white/10 pt-6"><p className="text-xs font-black uppercase tracking-[.14em] text-[#DDF65C]">New product</p><input className="admin-dark-field" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value, slug: form.slug || slugify(e.target.value) })} placeholder="Product title" required /><input className="admin-dark-field" value={form.slug} onChange={(e) => setForm({ ...form, slug: slugify(e.target.value) })} placeholder="slug" required /><input className="admin-dark-field" value={form.summary} onChange={(e) => setForm({ ...form, summary: e.target.value })} placeholder="Short summary" /><input className="admin-dark-field" type="number" min="0" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} placeholder="Price" /><button disabled={busy === 'create'} className="mt-5 bg-[#DDF65C] px-5 py-3 text-sm font-black text-[#102321]">Create draft</button></form></aside>
      {!editing ? <section className="bg-white p-10"><h2 className="text-3xl font-black">Create the first product.</h2></section> : <form onSubmit={save} className="bg-white"><div className="flex flex-wrap justify-between gap-4 border-b border-black/10 p-7 md:p-10"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#F06449]">Product editor</p><h2 className="mt-2 text-4xl font-black">{editing.title}</h2></div><div className="flex gap-4"><a href={`/shop/${editing.slug}`} target="_blank" className="text-sm font-black underline">Preview ↗</a><button disabled={busy === 'save'} className="bg-[#102321] px-6 py-3 text-sm font-black text-white">{busy === 'save' ? 'Saving…' : 'Save product'}</button></div></div>
        <nav className="flex overflow-x-auto border-b border-black/10 px-7 md:px-10">{[['essentials','Essentials'],['facts','Plan facts'],['media','Media'],['contents','Contents'],['packages','Packages + FAQ'],['publishing','Publishing']].map(([id,label]) => <button type="button" key={id} onClick={() => setSection(id)} className={`shrink-0 border-b-4 px-4 py-4 text-xs font-black ${section === id ? 'border-[#DDF65C]' : 'border-transparent text-black/40'}`}>{label}</button>)}</nav>
        <div className="p-7 md:p-10">{section === 'essentials' && <EditorSection title="Name, positioning and price" intro="The information clients see first in the plan catalogue."><div className="grid gap-x-6 md:grid-cols-2"><Field label="Title"><input className="elx-field" value={editing.title} onChange={(e) => set('title', e.target.value)} /></Field><Field label="SKU / plan ID"><input className="elx-field" value={editing.sku || ''} onChange={(e) => set('sku', e.target.value)} /></Field><Field label="Eyebrow"><input className="elx-field" value={editing.eyebrow} onChange={(e) => set('eyebrow', e.target.value)} /></Field><Field label="Home type"><input className="elx-field" value={editing.category} onChange={(e) => set('category', e.target.value)} placeholder="Bungalow, Maisonette, Duplex…" /></Field><Field label="Architectural style"><input className="elx-field" value={editing.style || ''} onChange={(e) => set('style', e.target.value)} /></Field><Field label="Currency"><input className="elx-field" value={editing.currency} onChange={(e) => set('currency', e.target.value.toUpperCase())} /></Field><Field label="Starting price"><input className="elx-field" type="number" min="0" step="0.01" value={editing.price} onChange={(e) => set('price', Number(e.target.value))} /></Field><Field label="Regular / compare-at price"><input className="elx-field" type="number" min="0" step="0.01" value={editing.regular_price ?? ''} onChange={(e) => set('regular_price', e.target.value ? Number(e.target.value) : null)} /></Field></div><Field label="Catalogue summary"><textarea className="elx-field min-h-24" value={editing.summary} onChange={(e) => set('summary', e.target.value)} /></Field><Field label="Full design story"><textarea className="elx-field min-h-40" value={editing.description} onChange={(e) => set('description', e.target.value)} /></Field></EditorSection>}
        {section === 'facts' && <EditorSection title="Dimensions and plan facts" intro="These power the catalogue filters and technical overview."><div className="grid gap-x-6 md:grid-cols-3"><NumberField label="Bedrooms" value={editing.bedrooms} change={(value) => set('bedrooms', value || 0)} /><NumberField label="Bathrooms" value={editing.bathrooms} change={(value) => set('bathrooms', value || 0)} step="0.5" /><NumberField label="Floors" value={editing.floors} change={(value) => set('floors', value || 1)} /><NumberField label="Floor area (m²)" value={editing.area_sqm} change={(value) => set('area_sqm', value)} /><NumberField label="Building width (m)" value={editing.width_m} change={(value) => set('width_m', value)} /><NumberField label="Building depth (m)" value={editing.depth_m} change={(value) => set('depth_m', value)} /><NumberField label="Plot width (m)" value={editing.plot_width_m} change={(value) => set('plot_width_m', value)} /><NumberField label="Plot depth (m)" value={editing.plot_depth_m} change={(value) => set('plot_depth_m', value)} /><NumberField label="Garage spaces" value={editing.garage_spaces} change={(value) => set('garage_spaces', value || 0)} /></div><Field label="Search tags (one per line)"><textarea className="elx-field min-h-28" value={(editing.tags || []).join('\n')} onChange={(e) => set('tags', lines(e.target.value))} /></Field></EditorSection>}
        {section === 'media' && <EditorSection title="Product gallery" intro="Use uploaded media or paste a public image URL. Select multiple uploaded images for the gallery."><div className="grid gap-x-6 md:grid-cols-2"><Field label="Cover image URL"><input className="elx-field" value={editing.cover_url || ''} onChange={(e) => set('cover_url', e.target.value || null)} /></Field><Field label="Preview video URL"><input className="elx-field" value={editing.preview_video_url || ''} onChange={(e) => set('preview_video_url', e.target.value || null)} /></Field><Field label="Choose cover from Media Library"><select className="elx-field" value="" onChange={(e) => e.target.value && set('cover_url', e.target.value)}><option value="">Select an image…</option>{media.filter((item) => item.kind === 'image').map((asset) => <option key={asset.id} value={asset.public_url}>{asset.title || asset.file_name}</option>)}</select></Field><Field label="Choose video from Media Library"><select className="elx-field" value="" onChange={(e) => e.target.value && set('preview_video_url', e.target.value)}><option value="">Select a video…</option>{media.filter((item) => item.kind === 'video').map((asset) => <option key={asset.id} value={asset.public_url}>{asset.title || asset.file_name}</option>)}</select></Field></div>{editing.cover_url && <img src={editing.cover_url} alt="Current product cover" className="mt-7 aspect-[3/1] w-full object-cover" />}<Field label="Gallery URLs (one per line)"><textarea className="elx-field min-h-28" value={(editing.gallery || []).map((item) => item.url).join('\n')} onChange={(e) => set('gallery', lines(e.target.value).map((url) => ({ url, type: url.match(/\.(mp4|webm|mov)$/i) ? 'video' : 'image', alt: editing.title })))} /></Field><a href="/admin/media" className="mt-6 inline-block text-sm font-black underline">Open Media Library ↗</a></EditorSection>}
        {section === 'contents' && <EditorSection title="Rooms, drawings and delivered files" intro="Be exact about what the plan package contains."><div className="grid gap-6 md:grid-cols-2"><LineField label="Rooms included" value={editing.rooms || []} change={(value) => set('rooms', value)} /><LineField label="Architectural drawings" value={editing.drawings || []} change={(value) => set('drawings', value)} /><LineField label="Delivered files" value={editing.included_files || []} change={(value) => set('included_files', value)} /><Field label="Additional specifications (Label: Value)"><textarea className="elx-field min-h-48" value={(editing.specifications || []).map((item) => `${item.label}: ${item.value}`).join('\n')} onChange={(e) => set('specifications', pairs(e.target.value, ':').map(([label,value]) => ({ label, value })))} /></Field></div></EditorSection>}
        {section === 'packages' && <EditorSection title="Purchase packages and questions" intro="Offer PDF, editable CAD and customization choices at different prices."><Field label="Packages — Label | Price | File types | Description"><textarea className="elx-field min-h-44" value={(editing.package_options || []).map((item) => `${item.label} | ${item.price} | ${item.fileTypes} | ${item.description}`).join('\n')} onChange={(e) => set('package_options', packageLines(e.target.value))} /></Field><div className="mt-7 grid gap-px bg-black/10 md:grid-cols-3">{(editing.package_options || []).map((item) => <div key={item.id} className="bg-[#F8F7F2] p-5"><small className="font-black uppercase tracking-[.1em] text-[#F06449]">{item.fileTypes}</small><strong className="mt-2 block text-xl">{item.label}</strong><span className="mt-4 block text-2xl font-black">{editing.currency} {item.price}</span></div>)}</div><Field label="FAQs — Question | Answer"><textarea className="elx-field min-h-40" value={(editing.faqs || []).map((item) => `${item.question} | ${item.answer}`).join('\n')} onChange={(e) => set('faqs', pairs(e.target.value, '|').map(([question,answer]) => ({ question, answer })))} /></Field></EditorSection>}
        {section === 'publishing' && <EditorSection title="Availability and catalogue position" intro="Control visibility, badges and the order of plans."><div className="grid gap-x-6 md:grid-cols-2"><Field label="Status"><select className="elx-field" value={editing.status} onChange={(e) => set('status', e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></Field><NumberField label="Sort order" value={editing.sort_order} change={(value) => set('sort_order', value || 0)} /></div><div className="mt-8 grid gap-3 md:grid-cols-2"><Check label="Feature in catalogue" checked={editing.featured} change={(value) => set('featured', value)} /><Check label="Best seller badge" checked={editing.best_seller} change={(value) => set('best_seller', value)} /><Check label="Digital / instant-delivery ready" checked={editing.instant_delivery} change={(value) => set('instant_delivery', value)} /><Check label="Customization available" checked={editing.customizable} change={(value) => set('customizable', value)} /></div><div className="mt-10 border-l-4 border-[#DDF65C] bg-[#F8F7F2] p-6 text-sm leading-6"><strong>Publishing checklist</strong><p className="mt-2 text-black/55">Add a model cover, dimensions, rooms, drawing list and at least one package before publishing. Construction suitability is confirmed only after site-specific professional adaptation.</p></div></EditorSection>}</div></form>}
    </div>
    <section className="overflow-x-auto bg-white p-6"><div className="flex justify-between"><h2 className="text-3xl font-black">Purchase requests</h2><span className="text-xs text-black/40">{requests.length}</span></div><table className="mt-5 w-full min-w-[1050px] text-left text-sm"><thead><tr className="text-[10px] uppercase tracking-[.12em] text-black/35"><th className="p-3">Product</th><th className="p-3">Package</th><th className="p-3">Client</th><th className="p-3">Contact</th><th className="p-3">Notes</th><th className="p-3">Status</th></tr></thead><tbody>{requests.map((request) => <tr key={request.id} className="border-t border-black/10"><td className="p-3 font-black">{request.product?.title || 'Product'}</td><td className="p-3"><strong>{request.package_label || 'Plan set'}</strong>{request.quoted_price != null && <span className="block text-xs text-black/45">{request.currency} {request.quoted_price}</span>}</td><td className="p-3">{request.name}</td><td className="p-3"><a href={`mailto:${request.email}`} className="block">{request.email}</a><span className="text-black/45">{request.whatsapp}</span></td><td className="max-w-xs whitespace-pre-line p-3 text-black/55">{request.notes || '—'}</td><td className="p-3"><select className="bg-[#F5F2E8] p-2 text-xs font-black" value={request.status} onChange={(e) => requestStatus(request.id, e.target.value)}>{requestStatuses.map((status) => <option key={status} value={status}>{status.replaceAll('_',' ')}</option>)}</select></td></tr>)}</tbody></table>{!requests.length && <p className="mt-6 text-sm text-black/40">No purchase requests yet.</p>}</section>
  </div>;
}

function Stat({ value, label }: { value: number; label: string }) { return <div className="bg-[#073C3E] px-5 py-4"><strong className="text-2xl">{value}</strong><small className="mt-1 block text-[9px] font-black uppercase tracking-[.12em] text-white/40">{label}</small></div>; }
function EditorSection({ title, intro, children }: { title: string; intro: string; children: React.ReactNode }) { return <section><h3 className="text-3xl font-black tracking-[-.04em]">{title}</h3><p className="mt-2 max-w-2xl text-sm text-black/45">{intro}</p><div className="mt-5">{children}</div></section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="mt-5 block text-xs font-black">{label}{children}</label>; }
function NumberField({ label, value, change, step = '1' }: { label: string; value: number | null; change: (value: number | null) => void; step?: string }) { return <Field label={label}><input className="elx-field" type="number" min="0" step={step} value={value ?? ''} onChange={(e) => change(e.target.value === '' ? null : Number(e.target.value))} /></Field>; }
function LineField({ label, value, change }: { label: string; value: string[]; change: (value: string[]) => void }) { return <Field label={`${label} (one per line)`}><textarea className="elx-field min-h-48" value={value.join('\n')} onChange={(e) => change(lines(e.target.value))} /></Field>; }
function Check({ label, checked, change }: { label: string; checked: boolean; change: (value: boolean) => void }) { return <label className={`flex cursor-pointer items-center gap-3 p-4 text-sm font-black ${checked ? 'bg-[#DDF65C]' : 'bg-[#F8F7F2]'}`}><input type="checkbox" checked={checked} onChange={(e) => change(e.target.checked)} />{label}</label>; }
function lines(value: string) { return value.split('\n').map((item) => item.trim()).filter(Boolean); }
function pairs(value: string, delimiter: string) { return lines(value).map((line) => { const [first, ...rest] = line.split(delimiter); return [first.trim(), rest.join(delimiter).trim()]; }).filter(([first, second]) => first && second); }
function packageLines(value: string): ProductPackage[] { return pairs(value, '|').map(([label, remainder], index) => { const [priceText, fileTypes, ...description] = remainder.split('|').map((part) => part.trim()); return { id: `${slugify(label)}-${index + 1}`, label, price: Math.max(0, Number(priceText) || 0), fileTypes: fileTypes || 'PDF', description: description.join(' | ') }; }); }
function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 120); }
