import { NextResponse } from 'next/server';
import { logAdminAudit } from '../../../../lib/admin-audit';
import { getAuthContext } from '../../../../lib/auth';
import { getSupabaseAdminClient } from '../../../../lib/supabase/admin';

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { user, roles } = await getAuthContext(); if (!user) return NextResponse.json({ error: 'Sign in required.' }, { status: 401 });
  if (!roles.some((role) => ['super_admin', 'admin'].includes(role))) return NextResponse.json({ error: 'Administrator access required.' }, { status: 403 });
  const { id } = await params; const body = await request.json().catch(() => ({})) as Record<string, unknown>; const admin = getSupabaseAdminClient(); if (!admin) return NextResponse.json({ error: 'Database unavailable.' }, { status: 503 });
  const { data: old } = await admin.from('digital_products').select('*').eq('id', id).maybeSingle(); if (!old) return NextResponse.json({ error: 'Product not found.' }, { status: 404 });
  const status = String(body.status ?? old.status); if (!['draft','published','archived'].includes(status)) return NextResponse.json({ error: 'Invalid product status.' }, { status: 400 });
  const textList = (value: unknown, fallback: string[]) => Array.isArray(value) ? value.map(String).map((item) => item.trim()).filter(Boolean).slice(0, 60) : fallback;
  const numberOrNull = (value: unknown) => value === '' || value === null || value === undefined ? null : Math.max(0, Number(value) || 0);
  const updates = { title: String(body.title ?? old.title).trim().slice(0, 250), eyebrow: String(body.eyebrow ?? old.eyebrow).trim().slice(0, 120), summary: String(body.summary ?? old.summary).trim().slice(0, 1000), description: String(body.description ?? old.description).trim().slice(0, 10000), category: String(body.category ?? old.category).trim().slice(0, 120), style: String(body.style ?? old.style).trim().slice(0, 120), sku: String(body.sku ?? old.sku).trim().slice(0, 80), price: Math.max(0, Number(body.price ?? old.price) || 0), regular_price: numberOrNull(body.regular_price), currency: String(body.currency ?? old.currency).toUpperCase().slice(0, 3), cover_url: String(body.cover_url ?? old.cover_url ?? '').trim().slice(0, 2000) || null, preview_video_url: String(body.preview_video_url ?? old.preview_video_url ?? '').trim().slice(0, 2000) || null, gallery: Array.isArray(body.gallery) ? body.gallery.slice(0, 24) : old.gallery, included_files: textList(body.included_files, old.included_files), rooms: textList(body.rooms, old.rooms), drawings: textList(body.drawings, old.drawings), tags: textList(body.tags, old.tags), specifications: Array.isArray(body.specifications) ? body.specifications.slice(0, 30) : old.specifications, package_options: Array.isArray(body.package_options) ? body.package_options.slice(0, 12) : old.package_options, faqs: Array.isArray(body.faqs) ? body.faqs.slice(0, 20) : old.faqs, bedrooms: Math.max(0, Number(body.bedrooms ?? old.bedrooms) || 0), bathrooms: Math.max(0, Number(body.bathrooms ?? old.bathrooms) || 0), floors: Math.max(0, Number(body.floors ?? old.floors) || 0), width_m: numberOrNull(body.width_m), depth_m: numberOrNull(body.depth_m), area_sqm: numberOrNull(body.area_sqm), plot_width_m: numberOrNull(body.plot_width_m), plot_depth_m: numberOrNull(body.plot_depth_m), garage_spaces: Math.max(0, Number(body.garage_spaces ?? old.garage_spaces) || 0), customizable: typeof body.customizable === 'boolean' ? body.customizable : old.customizable, instant_delivery: typeof body.instant_delivery === 'boolean' ? body.instant_delivery : old.instant_delivery, best_seller: typeof body.best_seller === 'boolean' ? body.best_seller : old.best_seller, status, featured: typeof body.featured === 'boolean' ? body.featured : old.featured, sort_order: Number.isInteger(Number(body.sort_order)) ? Number(body.sort_order) : old.sort_order, updated_by: user.id };
  if (!updates.title) return NextResponse.json({ error: 'Title is required.' }, { status: 400 });
  const { error } = await admin.from('digital_products').update(updates).eq('id', id); if (error) return NextResponse.json({ error: error.message }, { status: 400 });
  await logAdminAudit({ actorId: user.id, action: 'product.updated', entityType: 'digital_product', entityId: id, oldData: { title: old.title, status: old.status }, newData: updates, request });
  return NextResponse.json({ ok: true });
}
