import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { SiteShell } from '../../components/site-shell';
import { getPublishedProducts } from '../../lib/site-content';
import { resolveLocale } from '../../locale';
import ProductGallery from './product-gallery';
import PurchaseRequestForm from './purchase-request-form';

const money = (value: number, currency: string) => new Intl.NumberFormat('en', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value);
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const product = (await getPublishedProducts()).find((item) => item.slug === slug); return product ? { title: product.title, description: product.summary, alternates: { canonical: `/shop/${product.slug}` }, openGraph: { title: product.title, description: product.summary, url: `/shop/${product.slug}`, type: 'website', images: product.cover_url ? [{ url: product.cover_url, alt: product.title }] : undefined } } : { title: 'Plan not found' }; }

export default async function ProductPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams?: Promise<{ lang?: string | string[] }> }) {
  const [{ slug }, query, products] = await Promise.all([params, searchParams, getPublishedProducts()]); const locale = await resolveLocale(query?.lang); const product = products.find((item) => item.slug === slug); if (!product) notFound();
  const packages = product.package_options?.length ? product.package_options : [{ id: 'base', label: 'Digital plan set', price: product.price, fileTypes: 'PDF', description: 'Digital architectural drawing set.' }]; const related = products.filter((item) => item.id !== product.id && (item.bedrooms === product.bedrooms || item.category === product.category)).slice(0, 3);
  const productSchema = { '@context': 'https://schema.org', '@type': 'Product', sku: product.sku, name: product.title, description: product.summary, image: product.cover_url ? [product.cover_url] : undefined, category: product.category, brand: { '@type': 'Brand', name: 'Elx Studio' }, offers: packages.map((item) => ({ '@type': 'Offer', name: item.label, url: `https://elxholdings.com/shop/${product.slug}`, priceCurrency: product.currency, price: item.price, availability: 'https://schema.org/InStock', seller: { '@type': 'Organization', name: 'Elx Holdings' } })) };
  return <SiteShell locale={locale}><main className="bg-[#F8F7F2]"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} />
    <section className="px-5 py-8 md:px-10 md:py-12"><div className="mx-auto max-w-[1440px]"><div className="mb-7 text-xs font-bold text-black/45"><a href="/shop" className="underline">Plan shop</a> / {product.category} / {product.sku}</div><div className="grid gap-10 lg:grid-cols-[1.2fr_.8fr]"><ProductGallery title={product.title} cover={product.cover_url} gallery={product.gallery} video={product.preview_video_url} /><div className="lg:sticky lg:top-28 lg:self-start"><div className="flex gap-2 text-[10px] font-black uppercase tracking-[.13em]">{product.best_seller && <span className="bg-[#DDF65C] px-3 py-2">Best seller</span>}<span className="bg-[#102321] px-3 py-2 text-white">{product.sku}</span></div><p className="mt-6 text-xs font-black uppercase tracking-[.15em] text-[#F06449]">{product.style} / {product.category}</p><h1 className="mt-4 text-5xl font-black leading-[.9] tracking-[-.06em] md:text-7xl">{product.title}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-black/60">{product.summary}</p><div className="mt-7 flex items-baseline gap-3"><span className="text-xs font-black uppercase tracking-[.12em] text-black/40">Plans from</span><strong className="text-4xl">{money(product.price, product.currency)}</strong>{product.regular_price && <s className="text-black/35">{money(product.regular_price, product.currency)}</s>}</div><div className="mt-8 grid grid-cols-4 border-y border-black/15 py-5 text-center"><Fact value={product.bedrooms} label="Bedrooms" /><Fact value={product.bathrooms} label="Bathrooms" /><Fact value={product.floors} label="Floors" /><Fact value={`${product.area_sqm}m²`} label="Floor area" /></div><a href="#request" className="mt-8 block bg-[#102321] px-7 py-4 text-center text-sm font-black text-white">Choose files and request plan →</a><div className="mt-5 grid grid-cols-3 gap-4 text-center text-[10px] font-black uppercase tracking-[.1em] text-black/50"><span>Digital delivery</span><span>{product.customizable ? 'Customizable' : 'Stock plan'}</span><span>Files confirmed first</span></div></div></div></div></section>
    <section className="border-y border-black/10 bg-white px-5 py-16 md:px-10 md:py-20"><div className="mx-auto grid max-w-[1440px] gap-14 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-xs font-black uppercase tracking-[.15em] text-[#F06449]">The design</p><h2 className="mt-4 text-4xl font-black tracking-[-.05em] md:text-6xl">Built around real daily life.</h2><p className="mt-7 max-w-3xl text-lg leading-8 text-black/65">{product.description}</p><div className="mt-10 grid grid-cols-2 gap-px bg-black/10 sm:grid-cols-4"><FactBox label="Footprint" value={`${product.width_m} × ${product.depth_m}m`} /><FactBox label="Recommended plot" value={`${product.plot_width_m} × ${product.plot_depth_m}m`} /><FactBox label="Garage" value={`${product.garage_spaces} spaces`} /><FactBox label="Style" value={product.style} /></div></div><div className="grid gap-8 sm:grid-cols-2"><List title="Rooms included" items={product.rooms} /><List title="Drawing set" items={product.drawings} /></div></div></section>
    <section className="bg-[#073C3E] px-5 py-16 text-white md:px-10 md:py-20"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-black uppercase tracking-[.15em] text-[#DDF65C]">What you receive</p><h2 className="mt-4 text-5xl font-black leading-[.9] tracking-[-.055em]">A clear set, in the format you need.</h2><p className="mt-6 leading-7 text-white/55">Every package is checked before payment. This prevents buying an incompatible format and gives you a place to explain changes.</p></div><div className="grid gap-px bg-white/15 sm:grid-cols-2">{packages.map((item) => <div key={item.id} className="bg-[#073C3E] p-7"><p className="text-xs font-black uppercase tracking-[.14em] text-[#DDF65C]">{item.fileTypes}</p><h3 className="mt-3 text-2xl font-black">{item.label}</h3><p className="mt-3 text-sm leading-6 text-white/55">{item.description}</p><strong className="mt-6 block text-2xl">{money(item.price, product.currency)}</strong></div>)}</div></div></section>
    <section id="request" className="bg-[#DDF65C] px-5 py-16 md:px-10 md:py-20"><div className="mx-auto grid max-w-[1200px] gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-black uppercase tracking-[.16em]">Plan request</p><h2 className="mt-5 text-5xl font-black leading-[.9] tracking-[-.06em]">Choose the files. Tell us about the build.</h2><p className="mt-6 leading-7 text-black/60">We confirm the selected package, intended use and any customization before sending payment instructions.</p></div><PurchaseRequestForm productId={product.id} productTitle={product.title} packages={packages} currency={product.currency} /></div></section>
    {!!product.faqs?.length && <section className="bg-white px-5 py-16 md:px-10 md:py-20"><div className="mx-auto max-w-[1000px]"><p className="text-xs font-black uppercase tracking-[.15em] text-[#F06449]">Plan questions</p><h2 className="mt-4 text-5xl font-black tracking-[-.055em]">Before you build.</h2><div className="mt-8 border-t border-black/15">{product.faqs.map((item) => <details key={item.question} className="border-b border-black/15 py-5"><summary className="cursor-pointer list-none text-lg font-black">{item.question}<span className="float-right">+</span></summary><p className="mt-4 max-w-3xl leading-7 text-black/60">{item.answer}</p></details>)}</div></div></section>}
    {!!related.length && <section className="bg-[#F8F7F2] px-5 py-16 md:px-10 md:py-20"><div className="mx-auto max-w-[1440px]"><h2 className="text-5xl font-black tracking-[-.055em]">Related plans</h2><div className="mt-8 grid gap-6 md:grid-cols-3">{related.map((item) => <a key={item.id} href={`/shop/${item.slug}`}><div className="aspect-[3/2] overflow-hidden bg-[#102321]">{item.cover_url && <img src={item.cover_url} alt={item.title} className="h-full w-full object-cover" />}</div><p className="mt-4 text-[10px] font-black uppercase tracking-[.12em] text-[#F06449]">{item.sku} · {item.bedrooms} bedrooms</p><h3 className="mt-2 text-2xl font-black">{item.title}</h3><strong className="mt-2 block">From {money(item.price, item.currency)}</strong></a>)}</div></div></section>}
  </main></SiteShell>;
}
function Fact({ value, label }: { value: string | number; label: string }) { return <div><strong className="block text-xl">{value}</strong><span className="mt-1 block text-[9px] font-bold uppercase tracking-[.11em] text-black/40">{label}</span></div>; }
function FactBox({ label, value }: { label: string; value: string }) { return <div className="bg-white p-5"><span className="text-[9px] font-black uppercase tracking-[.12em] text-black/40">{label}</span><strong className="mt-2 block text-lg">{value}</strong></div>; }
function List({ title, items }: { title: string; items: string[] }) { return <div><h3 className="text-2xl font-black">{title}</h3><ul className="mt-5 border-t border-black/15">{items.map((item) => <li key={item} className="border-b border-black/15 py-3 text-sm font-bold">{item}</li>)}</ul></div>; }
