-- Rich architectural-plan catalogue, purchasable packages and request context.

alter table public.digital_products
  add column if not exists sku text not null default '',
  add column if not exists style text not null default 'Contemporary',
  add column if not exists bedrooms smallint not null default 0 check (bedrooms >= 0),
  add column if not exists bathrooms numeric(4,1) not null default 0 check (bathrooms >= 0),
  add column if not exists floors smallint not null default 1 check (floors >= 0),
  add column if not exists width_m numeric(8,2),
  add column if not exists depth_m numeric(8,2),
  add column if not exists area_sqm numeric(10,2),
  add column if not exists plot_width_m numeric(8,2),
  add column if not exists plot_depth_m numeric(8,2),
  add column if not exists garage_spaces smallint not null default 0 check (garage_spaces >= 0),
  add column if not exists rooms text[] not null default '{}',
  add column if not exists drawings text[] not null default '{}',
  add column if not exists tags text[] not null default '{}',
  add column if not exists regular_price numeric(12,2),
  add column if not exists customizable boolean not null default true,
  add column if not exists instant_delivery boolean not null default false,
  add column if not exists best_seller boolean not null default false,
  add column if not exists package_options jsonb not null default '[]'::jsonb,
  add column if not exists faqs jsonb not null default '[]'::jsonb;

alter table public.product_requests
  add column if not exists package_id text,
  add column if not exists package_label text,
  add column if not exists quoted_price numeric(12,2),
  add column if not exists currency text;

create index if not exists digital_products_catalog_idx on public.digital_products(company_id, status, bedrooms, floors, area_sqm);

-- Retain the earlier starter records in the manager without showing them publicly.
update public.digital_products set status = 'archived'
where company_id = '00000000-0000-4000-8000-000000000002'
  and slug in ('compact-three-bedroom-plan','modern-two-bedroom-starter','small-office-concept-pack');

insert into public.digital_products
  (company_id, slug, sku, title, eyebrow, summary, description, category, style, price, regular_price, currency, cover_url, bedrooms, bathrooms, floors, width_m, depth_m, area_sqm, plot_width_m, plot_depth_m, garage_spaces, rooms, drawings, tags, included_files, specifications, package_options, faqs, customizable, instant_delivery, best_seller, status, featured, sort_order)
values
  ('00000000-0000-4000-8000-000000000002','tamarind-three-bedroom-bungalow','ELX-101','Tamarind Three-Bedroom Bungalow','Warm-climate single-storey plan','A calm, generous bungalow organized around shaded outdoor living and an efficient family layout.','Tamarind balances a welcoming front veranda with a private bedroom wing and a bright open living core. Deep overhangs and cross-ventilation make it a strong starting point for warm-climate sites. The stock package is a concept and drawing set that must be adapted by qualified local professionals before construction.','Bungalow','Modern tropical',59,79,'USD','/shop/tamarind-bungalow.webp',3,2,1,14.8,13.2,168,20,25,2,array['Entrance porch','Open living and dining','Kitchen with pantry','Primary ensuite','Two bedrooms','Shared bathroom','Laundry','Rear veranda'],array['Dimensioned floor plan','Roof plan','Four elevations','Two building sections','Door and window schedule','Area schedule'],array['3 bedroom','single storey','tropical','veranda'],array['Printable PDF drawing set','Editable DWG source set','Room and area schedules'], '[{"label":"Roof","value":"Low-pitched hipped roof"},{"label":"Structure","value":"Masonry concept"},{"label":"Delivery","value":"Digital files"}]'::jsonb, '[{"id":"pdf","label":"PDF plan set","price":59,"fileTypes":"PDF","description":"Print-ready architectural drawing set."},{"id":"cad","label":"CAD + PDF plan set","price":89,"fileTypes":"DWG + PDF","description":"Editable source drawings plus the print-ready set."}]'::jsonb, '[{"question":"Can the plan be mirrored?","answer":"Yes. Select CAD + PDF and describe the required orientation in your request."},{"question":"Is this ready for approval?","answer":"A local architect or engineer must adapt and certify the plan for your site and authority."}]'::jsonb,true,true,true,'published',true,1),
  ('00000000-0000-4000-8000-000000000002','acacia-four-bedroom-maisonette','ELX-204','Acacia Four-Bedroom Maisonette','Contemporary two-storey family home','A confident four-bedroom home with expansive living spaces, a guest suite and shaded upper-level balconies.','Acacia is designed for families who want separation between social and private spaces without wasting circulation. The ground floor combines entertaining, service and guest functions; the upper floor gives the family a private lounge and three bedrooms.','Maisonette','Contemporary',99,129,'USD','/shop/acacia-maisonette.webp',4,3.5,2,16.4,14.6,286,22,28,2,array['Double-height entrance','Living room','Dining room','Island kitchen','Pantry and laundry','Guest ensuite','Family lounge','Primary suite','Two bedrooms','Three balconies'],array['Ground and first floor plans','Roof plan','Four elevations','Two sections','Stair details','Door and window schedule','Area schedule'],array['4 bedroom','two storey','maisonette','family home'],array['Printable PDF drawing set','Editable DWG source set','Room and area schedules','Exterior reference render'], '[{"label":"Roof","value":"Flat and shallow roof planes"},{"label":"Structure","value":"Reinforced concrete concept"},{"label":"Delivery","value":"Digital files"}]'::jsonb, '[{"id":"pdf","label":"PDF plan set","price":99,"fileTypes":"PDF","description":"Complete print-ready architectural set."},{"id":"cad","label":"CAD + PDF plan set","price":149,"fileTypes":"DWG + PDF","description":"Editable drawings and print-ready sheets."},{"id":"custom","label":"Plan + customization review","price":249,"fileTypes":"DWG + PDF","description":"Plan package plus an initial adaptation consultation."}]'::jsonb, '[{"question":"Can room sizes be changed?","answer":"Yes. Choose the customization package and explain the plot and room changes required."},{"question":"Are structural drawings included?","answer":"No. Structural design must be prepared for the final site and local conditions."}]'::jsonb,true,true,true,'published',true,2),
  ('00000000-0000-4000-8000-000000000002','savana-two-bedroom-starter','ELX-082','Savana Two-Bedroom Starter Home','Compact and attainable plan','A practical small home with a clear structure, comfortable rooms and a buildable compact footprint.','Savana focuses the budget on useful space. The plan places an open living zone at the front, keeps wet areas together and leaves room for simple future adaptation. It suits a compact suburban or rural plot.','Starter home','Modern vernacular',35,45,'USD','/shop/savana-starter.webp',2,1,1,9.6,10.8,84,14,18,0,array['Covered porch','Living and dining','Compact kitchen','Two bedrooms','Shared bathroom','Utility court'],array['Dimensioned floor plan','Roof plan','Four elevations','One section','Door and window schedule'],array['2 bedroom','affordable','compact','single storey'],array['Printable PDF drawing set','Editable DWG source set','Area schedule'], '[{"label":"Roof","value":"Simple pitched roof"},{"label":"Structure","value":"Masonry concept"},{"label":"Delivery","value":"Digital files"}]'::jsonb, '[{"id":"pdf","label":"PDF plan set","price":35,"fileTypes":"PDF","description":"Print-ready starter drawing set."},{"id":"cad","label":"CAD + PDF plan set","price":55,"fileTypes":"DWG + PDF","description":"Editable source drawing and PDF sheets."}]'::jsonb, '[{"question":"Can a third bedroom be added later?","answer":"The concept can be assessed for an extension after the final site orientation is known."}]'::jsonb,true,true,false,'published',true,3),
  ('00000000-0000-4000-8000-000000000002','zuri-five-bedroom-courtyard-villa','ELX-510','Zuri Five-Bedroom Courtyard Villa','Premium courtyard residence','A layered luxury home that brings daylight, privacy and landscape into the centre of daily life.','Zuri organizes generous living and bedroom suites around a protected courtyard. Shaded terraces, controlled views and a clear service route make the home feel calm even at a substantial scale.','Villa','Contemporary tropical',169,219,'USD','/shop/zuri-courtyard.webp',5,5.5,2,25.2,23.8,548,32,36,3,array['Arrival court','Formal lounge','Open family living','Courtyard','Show kitchen','Service kitchen','Five ensuite bedrooms','Study','Gym','Family lounge','Staff room','Laundry','Three-car garage'],array['Ground and first floor plans','Roof plan','Six elevations','Three sections','Reflected ceiling concept','Door and window schedule','Area schedule'],array['5 bedroom','luxury','courtyard','villa'],array['Printable PDF drawing set','Editable DWG source set','Room and area schedules','Exterior reference renders'], '[{"label":"Roof","value":"Mixed low-slope roof"},{"label":"Structure","value":"Reinforced concrete concept"},{"label":"Delivery","value":"Digital files"}]'::jsonb, '[{"id":"pdf","label":"PDF plan set","price":169,"fileTypes":"PDF","description":"Premium print-ready architectural set."},{"id":"cad","label":"CAD + PDF plan set","price":239,"fileTypes":"DWG + PDF","description":"Editable source files and PDF sheets."},{"id":"custom","label":"Plan + customization review","price":399,"fileTypes":"DWG + PDF","description":"Plan package plus an initial architect-led adaptation review."}]'::jsonb, '[{"question":"Is the courtyard optional?","answer":"It is central to the design, but its dimensions and enclosure can be adapted to the climate and plot."},{"question":"Do the files include engineering?","answer":"No. The structural and services designs are developed after site-specific architectural adaptation."}]'::jsonb,true,true,false,'published',true,4),
  ('00000000-0000-4000-8000-000000000002','kifaru-three-bedroom-duplex','ELX-D312','Kifaru Three-Bedroom Duplex','Two complete family units','A balanced duplex concept with two independent three-bedroom homes and a strong shared street presence.','Kifaru makes efficient use of a medium urban plot while protecting each household’s privacy. Mirrored planning simplifies structure and services without making the facade feel repetitive.','Duplex','Contemporary',129,159,'USD','/shop/kifaru-duplex.webp',6,5,2,18.6,16.8,372,24,26,4,array['Two private entrances','Two living rooms','Two dining rooms','Two kitchens','Two primary suites','Four secondary bedrooms','Two family lounges','Four balconies'],array['Ground and first floor plans','Roof plan','Four elevations','Two sections','Stair details','Door and window schedule','Unit area schedules'],array['duplex','multi-family','investment','two storey'],array['Printable PDF drawing set','Editable DWG source set','Unit and room schedules','Exterior reference render'], '[{"label":"Units","value":"2 mirrored homes"},{"label":"Structure","value":"Reinforced concrete concept"},{"label":"Delivery","value":"Digital files"}]'::jsonb, '[{"id":"pdf","label":"PDF plan set","price":129,"fileTypes":"PDF","description":"Complete duplex drawing set."},{"id":"cad","label":"CAD + PDF plan set","price":189,"fileTypes":"DWG + PDF","description":"Editable source set and PDFs."},{"id":"custom","label":"Plan + customization review","price":319,"fileTypes":"DWG + PDF","description":"Plan files plus an adaptation review for your plot."}]'::jsonb, '[{"question":"Can the units have different layouts?","answer":"Yes, but this becomes a custom adaptation because the shared structure and services must be coordinated."}]'::jsonb,true,true,false,'published',true,5),
  ('00000000-0000-4000-8000-000000000002','nuru-narrow-lot-three-bedroom','ELX-N303','Nuru Narrow-Lot Three-Bedroom Home','Urban infill plan','A slim, light-filled home designed to make a constrained urban plot feel deliberate rather than compromised.','Nuru uses vertical space, screened openings and a roof terrace to create privacy and daylight on a narrow site. The compact width makes it useful for infill plots while preserving family-sized rooms.','Narrow lot','Minimal contemporary',89,109,'USD','/shop/narrow-lot-house.webp',3,2.5,2,6.8,18.4,196,9,24,1,array['Entry court','Open living and dining','Linear kitchen','Laundry','Primary suite','Two bedrooms','Study landing','Roof terrace'],array['Ground and first floor plans','Roof terrace plan','Four elevations','Two sections','Stair details','Door and window schedule'],array['3 bedroom','narrow lot','urban','roof terrace'],array['Printable PDF drawing set','Editable DWG source set','Room and area schedules','Exterior reference render'], '[{"label":"Plot type","value":"Narrow urban lot"},{"label":"Structure","value":"Reinforced concrete concept"},{"label":"Delivery","value":"Digital files"}]'::jsonb, '[{"id":"pdf","label":"PDF plan set","price":89,"fileTypes":"PDF","description":"Print-ready narrow-lot drawing set."},{"id":"cad","label":"CAD + PDF plan set","price":129,"fileTypes":"DWG + PDF","description":"Editable files plus PDF sheets."}]'::jsonb, '[{"question":"Can the house be built without the roof terrace?","answer":"Yes. The roof and stair can be simplified during site adaptation."}]'::jsonb,true,true,false,'published',true,6)
on conflict (company_id, slug) do update set
  sku = excluded.sku, title = excluded.title, eyebrow = excluded.eyebrow, summary = excluded.summary,
  description = excluded.description, category = excluded.category, style = excluded.style,
  price = excluded.price, regular_price = excluded.regular_price, currency = excluded.currency,
  cover_url = excluded.cover_url, bedrooms = excluded.bedrooms, bathrooms = excluded.bathrooms,
  floors = excluded.floors, width_m = excluded.width_m, depth_m = excluded.depth_m,
  area_sqm = excluded.area_sqm, plot_width_m = excluded.plot_width_m, plot_depth_m = excluded.plot_depth_m,
  garage_spaces = excluded.garage_spaces, rooms = excluded.rooms, drawings = excluded.drawings,
  tags = excluded.tags, included_files = excluded.included_files, specifications = excluded.specifications,
  package_options = excluded.package_options, faqs = excluded.faqs, customizable = excluded.customizable,
  instant_delivery = excluded.instant_delivery, best_seller = excluded.best_seller,
  status = excluded.status, featured = excluded.featured, sort_order = excluded.sort_order;
